---
abstract: "Text::CSV wrapper similar to R's read.table and write.table"
author:
  - 'M. Riester <limaone@cpan.org>'
build_requires:
  File::Temp: 0
  Test::LongString: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-CSV-R
provides:
  Text::CSV::R:
    file: lib/Text/CSV/R.pm
    version: 0.02
  Text::CSV::R::Matrix:
    file: lib/Text/CSV/R/Matrix.pm
    version: 0.02
requires:
  Carp: 0
  Scalar::Util: 0
  Text::CSV: 1
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/lima1/p5-text-csv-r
version: 0.02
