--- #YAML:1.0
name:               Text-CSV-R
version:            0.01
abstract:           Text::CSV wrapper similar to R's read.table and write.table
author:
    - M. Riester <limaone@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:              0
    File::Temp:        0
    Scalar::Util:      0
    Test::LongString:  0
    Test::More:        0
    Test::NoWarnings:  0
    Text::CSV:         1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
